name: Dependency compatibility

on:
  schedule:
    - cron: '38 3 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compatibility:
    permissions:
      contents: read
      issues: write
    uses: sympress/workflows/.github/workflows/dependency-canary.yml@cd809f3986df3ea617d2d26bdf21ab69cae19c1e
    with:
      php_version: '8.5'
